server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Database?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 683125cc
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
verify:
  code:
    prefix: verify_code # 缓存中key前缀
    type: jpg # 验证码格式
    timeout: 60 # 验证码过期时间，单位秒